# Data sources

This dataset is from telephone interviews of the January 2020 Political Survey conducted by Abt Associates and submitted to the Pew Research Center from January 8th to January 13th, 2020. The dataset contains information gathered from a representative sample 1,504 adults living in the United States. These adults were sampled from a population of people aged 18 and over, living in the US, and with access to either a landline or a cell phone. These samples were provided by Survey Sampling International. The numbers from the landline samples were obtained by randomly drawing area code + exchange + two-digit block numbers, and the rest who have access to both landlines and cell phones may still be possible to be drawn during sampling process of cellular samples. Landline numbers drawn with an exchange in a high density Hispanic area or associated with a Hispanic surname were flagged by Marketing Systems Group to be assigned to bilingual interviewers. The interviews were conducted in both English and Spanish, depending on the language preferences of the interviewees. The questionnaire was developed by the Pew Research Center in consultation with Abt Associates, and was carefully pretested by experienced interviewers to judge the quality of the answers and how well have the interviewees understood the questions. 

During the interviewing process, numbers were called at most seven times before anybody picks up the phone. The Hispanic-flagged sample records and Spanish language callbacks were given three more additional call attempts. All call attempts were made at different time to ensure maximum possibility of getting picked up. All respondents who completed the survey were awarded a mash incentive of $5 for their participation. There were two weights created for this survey to address the probabilities of selection associated with the number of family members in a household and the overall telephone usage. The second stage weighting was to balance the samples to match national population parameters, such as sex, age, education, etc.

The raw dataset contains in total 115 columns and about 1,500 observations. Among the 115 variables, along with the basic information of the interviewee, were answers to all questions of the questionnaire. Almost all variables were regarded as numeric variables, yet as the questions were qualitative, there would be type transformation of data needed in the following investigation of the dataset. Furthermore, many variables contain more than half missing values out of all observations, which will be further explained in later sections. Additionally, our investigation will not be using all available variables in the dataset. A selection of variables will be made based on the research questions that we hope to answer. 

We are also aware of potential sources of bias for a survey investigation like this. As reported in the survey's methodology, there is random sampling error, and the margin of error is estimated to be +- 2.91 percentage points. In addition, other errors may include response bias, reporting inaccuracy, or misunderstanding of question wording, which may potentially affect the quality of the survey results. Being aware of these issues, we'll also process the data with caution.


